### ISSUE TITLE
Add support for SSS sets

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-max#108]

**Comment by luisbarrancos** [comment]
Hi @usakhelo. No, they are a different thing. When computing the light transport on the geometry, each object is considered a separate volume. SSS sets allow different objects to be grouped into a single set, so that the BSSRDF when evaluated will evaluate all the difference meshes as if they were a single volume to traverse and compute the lighting/shading.

**Comment by dictoon** [comment]
To expand slightly on @luisbarrancos's answer: technically an SSS set is just a label, i.e. a string. It's simply a parameter on object instances. All object instances with the same SSS set label will be treated as a single object during SSS computations.

Try assigning a SSS set to an object instance in appleseed.studio and see what effect this has on the project file. Alternatively you can check the SSS set test scenes in the test suite.

**Comment by usakhelo** [comment]
Got it thanks. Sample scene shows the difference clearly.
Probably text property should be added to appleseed object properties modifier?

**Comment by dictoon** [comment]
Yes exactly!

**Comment by juancarlosgzrz** [comment]
Issue done!
